imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: routing_auto.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [AcmeMainBundle, CmfCreateBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Add Symfony-Cmf
doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            # connection: default
            caches:
                meta: liip_doctrine_cache.ns.meta
                nodes: liip_doctrine_cache.ns.nodes
        workspace: default
        username: admin
        password: admin
    odm:
        auto_mapping: true

liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
        nodes:
            type: file_system

cmf_core:
    persistence:
        phpcr:
            enabled: true
    # enable when using the workflow
    publish_workflow:
        enabled: true

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 200
            router.default: 100
    dynamic:
        enabled: true
        # disable sonata_admin for routes if not used
#        persistence:
#            phpcr:
#                use_sonata_admin: false
        templates_by_class:
            Acme\MainBundle\Document\Page: AcmeMainBundle:Page:page.html.twig

cmf_create:
    persistence:
        phpcr:
            image: false

fos_rest:
    view:
        formats:
            json: true

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts: [admin]

sonata_admin:
    title: MyCmf
    title_logo:  /bundles/acmemain/ico/apple-touch-icon-57-precomposed.png
    templates:
        # default global templates
        user_block: AcmeMainBundle:Admin:user_block.html.twig
        layout:     AcmeMainBundle:Admin:admin_layout.html.twig
    extensions:
        cmf_core.admin_extension.publish_workflow.time_period:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishTimePeriodInterface
        cmf_core.admin_extension.publish_workflow.publishable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
        cmf_menu.admin_extension.menu_node_referrers:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
            # hide the dashboard tree for customers
            - { position: right, type: sonata_admin_doctrine_phpcr.tree_block }
        groups:
            content:
                label: Content
                items:
                    - acme_main.page_admin
            content_blocks:
                label: Content blocks
                items:
                    - cmf_block.simple_admin
                    - cmf_block.container_admin
                    - cmf_block.reference_admin
                    - cmf_block.action_admin
            routing:
                label: URLs
                items:
                    - cmf_routing.route_admin
                    - cmf_routing.redirect_route_admin
            menu:
                label: Menu
                items:
                    - cmf_menu.menu_admin
                    - cmf_menu.node_admin

sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Acme\MainBundle\Document\Page:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock
        Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock
        Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route:
            valid_children:
                - Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route
                - Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute
        Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:
            valid_children: []
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\Menu:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode