acme_main:
    resource: "@AcmeMainBundle/Resources/config/routing.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_js_routing:
    resource: @FOSJsRoutingBundle/Resources/config/routing/routing.xml

cmf_tree:
    resource: .
    type: 'cmf_tree'

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

_imagine:
    resource: .
    type:     imagine

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
